services:
  - type: web
    name: todolist
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn todolist.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
